server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:./database/job
    driver-class-name: org.h2.Driver
    username: yzh
    password: 123456
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true